name: compile

on:
  push:
    paths:
      - 'compileMbedtls.sh'
      - '.github/workflows/compile-mbedtls.yml'
      - '**/src/**/*.c'
jobs:
  compile:

    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            library-ext: so
            compile-flags:
          - platform: macos-latest
            compile-flags: DLEXT=dylib OSARCH=darwin
            library-ext: dylib

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Compile
        shell: bash
        run: ${{ matrix.compile-flags }} ./compileMbedtls.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: kotlin-mbedtls/src/main/resources/**/*.${{ matrix.library-ext }}
          if-no-files-found: error
